application: ga-powerpanel-dev
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /openid/__cron_check_licenses/
  script: main.py
  login: admin

- url: /login/.*
  script: main.py
  secure: always

- url: /.*
  script: main.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?django/.*
- ^(.*/)?marketplace/.*
- ^(.*/)*tests.py
