application: ga-powerpanel-dev
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /appadmin/docs
  login: admin
  static_dir: _build/html

- url: /appadmin/.*
  script: main.py
  login: admin

- url: /openid/__manifest/
  script: main.py
  login: admin

- url: /openid/__cron_check_licenses/
  script: main.py
  login: admin

- url: /__precache_all_domains/
  script: main.py
  login: admin

- url: /__precache_domain/
  script: main.py
  login: admin

- url: /login/.*
  script: main.py
  secure: always

- url: /.*
  script: main.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?django/.*
- ^(.*/)?lib/Crypto/.*
- ^(.*/)?static/closure-library/.*
- ^(.*/)?marketplace/.*
- ^(.*/)?util/.*
- ^(.*/)*tests.py
